name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "releases/**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    env:
      DOTNET_SDK_VERSION: "10.0.300"
      IMAGE_NAME: dotnet-sdk-extended

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          platforms: linux/amd64
          tags: ${{ env.IMAGE_NAME }}:${{ env.DOTNET_SDK_VERSION }}-ci
          build-args: |
            DOTNET_SDK_VERSION=${{ env.DOTNET_SDK_VERSION }}
      
      - name: Print versions of the tools
        run: |
          docker run --rm "${{ env.IMAGE_NAME }}:${{ env.DOTNET_SDK_VERSION }}-ci" /bin/bash -lc '
            source ~/.bashrc
            echo "******* Environment variables ******"
            echo "DOTNET_SDK_VERSION=${DOTNET_SDK_VERSION}";
            echo "NODE_VERSION=${NODE_VERSION}";
            echo "NPM_VERSION=${NPM_VERSION}";
            echo "SEVENZIP_VERSION=${SEVENZIP_VERSION}";
            echo "SQLCMD_VERSION=${SQLCMD_VERSION}";
            echo "TAR_VERSION=${TAR_VERSION}";
            echo "WIM_VERSION=${WIM_VERSION}";
            echo "ZIP_VERSION=${ZIP_VERSION}";
            echo "";
            echo "PATH=$PATH";
            echo "";
            echo "******* .NET ******"
            dotnet --info
            echo "";
            echo "******* Node.JS ******"
            node -v
            echo "";
            echo "******* NPM ******"
            npm -v
            echo "";
            echo "******* sqlcmd ******"
            sqlcmd --version 2>&1
            echo "";
            echo "******* 7-Zip ******"
            7z i
            echo "";
            echo "******* Tar ******"
            tar --version
            echo "";
            echo "******* WIM ******"
            wimlib-imagex --version
            echo "";
            echo "******* Zip ******"
            zip --version
          '
